#!	/usr/bin/env python

import sys
import cx_Oracle

query = '''
select cratelabel, bus_loop, module_crate, function 
from crates_v
where compname = :fecname
order by bus_loop, module_crate
'''

fecname = sys.argv[1]

con = cx_Oracle.connect('copub/co')
cur = con.cursor()

cur.execute(query, fecname = fecname)
for label, loop, rti, desc in cur.fetchall():
	if loop is None:
		continue
	print '%-10s %1d %02d' % (label, loop, rti)

